# Generated by Django 5.0.4 on 2024-05-10 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='url',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
