# Generated by Django 5.0.4 on 2024-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_category_remove_genre_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(default=models.CharField(max_length=100, verbose_name='Название'), max_length=100, verbose_name='Название на английском'),
        ),
    ]
