# Generated by Django 5.0.4 on 2024-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_title_eng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title_eng',
            field=models.CharField(default='', max_length=100, verbose_name='Название на английском'),
        ),
    ]
