# Generated by Django 5.0.4 on 2024-05-07 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_company_faq_promo_coupon_review_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='definition',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='term',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='date_added',
        ),
        migrations.AddField(
            model_name='faq',
            name='date_answer',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='faq',
            name='date_question',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='news_item',
            name='image',
            field=models.ImageField(default='images/cinema.jpg', upload_to='images'),
        ),
    ]
