# Generated by Django 5.0.4 on 2024-05-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_definition_faq_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='date_answer',
        ),
        migrations.AlterField(
            model_name='faq',
            name='date_question',
            field=models.DateField(auto_now_add=True),
        ),
    ]
