# Generated by Django 5.0.4 on 2024-05-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_company',
            options={'verbose_name': 'О компании', 'verbose_name_plural': 'О компании'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
        migrations.AlterModelOptions(
            name='news_item',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='promo_coupon',
            options={'verbose_name': 'Промокод и купон', 'verbose_name_plural': 'Промокоды и купоны'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
